apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hooman-cat-prod # Change name to yours
resources:
  - ../base
patches:

  # Replaces the hostname for our route
  - target:
      kind: Route
      version: v1
      group: route.openshift.io
    patch: |-
      - op: replace
        path: /spec/host
        value: mycats-prod.apps.edu-lab-2.mdlwr.se

  # Add container-arguments specific to test
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value: 
          - "-comment='😻 You will only find Prod-cats here'"
          - "-title='A Prod-Cat walks into a bar'"
          - "-url=https://images.freeimages.com/365/images/previews/141/garfield-cartoon-free-vectors-download-31178.jpg"